# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7f5f303f492173f023ea750664bdff6c"
name = "PV Product API"
handle = "pv-product-api"
application_url = "https://carl-talking-frame-wma.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://carl-talking-frame-wma.trycloudflare.com/auth/callback", "https://carl-talking-frame-wma.trycloudflare.com/auth/shopify/callback", "https://carl-talking-frame-wma.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
