# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "632d2e10859229a9d8b27c0af8625609"
name = "Product Details Fetcher"
handle = "product-details-fetcher-1"
application_url = "https://infrared-thongs-sleep-picked.trycloudflare.com"
embedded = true
embedded_redirect_url = "/product-details-fetcher"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_orders,read_product_listings,read_products,write_inventory,write_products"

[auth]
redirect_urls = ["https://infrared-thongs-sleep-picked.trycloudflare.com/auth/callback", "https://infrared-thongs-sleep-picked.trycloudflare.com/auth/shopify/callback", "https://infrared-thongs-sleep-picked.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[ui]
  [ui.nav]
  title = "Product Details Fetcher"
  url = "/app/product-details-fetcher"

  [[ui.nav.menu]]
  title = "Product Details Fetcher"
  url = "/product-details-fetcher"

  [[ui.nav.menu]]
  title = "Store Setup"
  url = "/app/store-setup"
